[package]
name = "neruda"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = "1.0.0"
rparse = { path = "../", features = ["serde"]}
serde = { version = "*", features = ["derive"] }
serde_json = "*"
